name: Terraform Apply

on:
  push:
    branches:
      - master
      
jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform  # Update this path if necessary

      - name: Apply Terraform configuration
        env:
          ASHOK_AWS_ACCESS_KEY_ID: ${{ secrets.ASHOK_AWS_ACCESS_KEY_ID }}
          ASHOK_AWS_SECRET_ACCESS_KEY: ${{ secrets.ASHOK_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
          AWS_REGION: ap-south-1
          TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}  # Optional: Passing secret key as Terraform variable
        run: terraform apply -auto-approve
        working-directory: ./terraform  # Update this path if necessary

      - name: Get SSH Private Key
        id: private_key
        run: echo "::set-output name=private_key::$(terraform output -raw strapi_private_key)"
        working-directory: ./terraform  # Ensure this matches your Terraform configuration path

      - name: Save SSH Private Key
        run: echo "${{ steps.private_key.outputs.private_key }}" > private_key.pem
